### ISSUE TITLE
[CH09]타입 변환과 단축 평가

### ISSUE THREAD

**Issue by yuzunsang** [yuzunsang/JS-deep-dive-study#13]
[퀴즈 예시]
Q. 여기에 퀴즈 설명을 적으세요.

적을 코드가 있다면 밑에 적어주세요.
(백틱 3개로 코드를 감싸면 코드 양식을 적을 수 있습니다.)
```
// 예시 코드
const arr = [1, 2, 3];
console.log("Hello");
```
아래 코드를 복붙해서 정답을 적어주세요.
```
<details>
	<summary>정답</summary>
	<div markdown="1">    
	정답 설명
	</div>
</details>
```

**Comment by yuzunsang** [comment]
Q. 다음 코드의 실행 결과는?

```
let i = 1, j = 2;

if ((--j - i++) && (++j)) i = i-- - --j;
else i = i + j;

console.log(i);
```

<details>
	<summary>정답</summary>
	<div markdown="1">    
	3
	</div>
</details>

**Comment by J-yun-ji** [comment]
Q1. 다음 코드의 실행 결과는 ?
```
console.log(`1 + 1 = ${1 + 1}`);

console.log(typeof(NaN +''));
```
<br>

Q2. 다음 코드의 실행 결과는 ?
```
console.log('4' * 5);
console.log('*' * 7);

```


<details>
	<summary>Q1 정답</summary>
	<div markdown="1">    
	1 + 1 = 2<br>
string
	</div>
</details>
<details>
	<summary>Q2 정답</summary>
	<div markdown="1">    
	20<br>NaN
	</div>
</details>
