### ISSUE TITLE
[CH10]객체 리터럴

### ISSUE THREAD

**Issue by yuzunsang** [yuzunsang/JS-deep-dive-study#14]
[퀴즈 예시]
Q. 여기에 퀴즈 설명을 적으세요.

적을 코드가 있다면 밑에 적어주세요.
(백틱 3개로 코드를 감싸면 코드 양식을 적을 수 있습니다.)
```
// 예시 코드
const arr = [1, 2, 3];
console.log("Hello");
```
아래 코드를 복붙해서 정답을 적어주세요.
```
<details>
	<summary>정답</summary>
	<div markdown="1">    
	정답 설명
	</div>
</details>
```

**Comment by yuzunsang** [comment]
Q. 객체의 프로퍼티에 접근하는 올바른 방법이 아닌 것은?

```
const user = {
  age: 25,
  "name": "Yoo",
  1: true,
  "my-hometown": "pyeongtaek",
  "my hobby": "running",
};
```
[보기]
1. user.age
2. user['name']
3. user['my-hometown']
4. user.1
5. user["my hobby"]

<details>
	<summary>정답</summary>
	<div markdown="1">    
	4번
(user[1]로 접근 가능하다)
	</div>
</details>

**Comment by sueonnn** [comment]
Q. 실행 결과는?

```var person = {
'last-name' : 'lee',
 1 : 10
};

console.log(person.'last-name);
console.log(person.last-name);

**Comment by bo-eun** [comment]
Q. person1 객체의 boeun값을 구하는 방법을 서술하시오.
````
let key = "name";
let person1 = {
  [key] : "boeun"
};

````

<details>
	<summary>정답</summary>
	<div markdown="1">    
	  console.log(person1[key])
	</div>
</details>
