### ISSUE TITLE
[CH11]원시 값과 객체의 비교

### ISSUE THREAD

**Issue by yuzunsang** [yuzunsang/JS-deep-dive-study#15]
[퀴즈 예시]
Q. 여기에 퀴즈 설명을 적으세요.

적을 코드가 있다면 밑에 적어주세요.
(백틱 3개로 코드를 감싸면 코드 양식을 적을 수 있습니다.)
```
// 예시 코드
const arr = [1, 2, 3];
console.log("Hello");
```
아래 코드를 복붙해서 정답을 적어주세요.
```
<details>
	<summary>정답</summary>
	<div markdown="1">    
	정답 설명
	</div>
</details>
```

**Comment by bo-eun** [comment]
Q1. 아래 코드 결과가 어떻게 나오는지 예상해보고 예상한 결과가 나온 이유를 설명하세요.
```
var str = "string";
console.log(str[0]); // s
str[0] = "S";
**console.log(str);**
```
<details>
	<summary>정답</summary>
	<div markdown="1">    
	string
	</div>
</details>

**Comment by yuzunsang** [comment]
Q. 얕은 복사(Shallow Copy)와 깊은 복사(Deep Copy)에 대해 설명해보시오.
<details>
	<summary>정답</summary>
	<div markdown="1">    
	객체의 경우, 얕은 복사는 <strong>참조값 자체를 복사</strong>해오는 것이고 깊은 복사는 <strong>객체로부터 1 depth까지 복사</strong>를 해오는 것입니다.<br />
원시값이 할당된 변수의 경우, 다른 변수에 할당하는 것을 깊은 복사, 객체를 할당한 변수를 다른 변수에 할당하는 경우, 얕은 복사라고도 합니다.
	</div>
</details>
