### ISSUE TITLE
[CH06]데이터 타입

### ISSUE THREAD

**Issue by yuzunsang** [yuzunsang/JS-deep-dive-study#7]
[퀴즈 예시]
Q. 여기에 퀴즈 설명을 적으세요.

적을 코드가 있다면 밑에 적어주세요.
(백틱 3개로 코드를 감싸면 코드 양식을 적을 수 있습니다.)
```
// 예시 코드
const arr = [1, 2, 3];
console.log("Hello");
```
아래 코드를 복붙해서 정답을 적어주세요.
```
<details>
	<summary>정답</summary>
	<div markdown="1">    
	정답 설명
	</div>
</details>
```

**Comment by J-yun-ji** [comment]
Q1. 아래 코드의 결과는 무엇인가요?

```
var octal = 0o101;
 
console.log(octal); 
```
1) 0o101
2) 65



<br>
<br>

Q2. 일반 따옴표와 백틱의 차이점은 무엇인가요?

<br>
<br>
<details>
	<summary>Q1 정답</summary>
	<div markdown="1">
        2번<br>
	0o101은 8진수이므로 모든 진수를 10진수로 표현하는 자바스크립트에선 10진수로 변환된 65가 출력됨.
	</div>
</details>
<details>
	<summary>Q2 정답</summary>
	<div markdown="2">    
	일반 따옴표는 개행 문자(\n)를 사용해야만 줄바꿈을 할 수 있는 반면 백틱은 개행 문자 없이 줄바꿈 및 공백을 인식함.
	</div>
</details>
